name: discord-client-wrapper ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm ci

    - name: lint project
      run: npm run prestart

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: create env file
      run: |
        touch .env
        echo CLIENT_TOKEN =${{ secrets.CLIENT_TOKEN }} >> .env
        echo SERVER_ID =${{ secrets.SERVER_ID }} >> .env
        echo SERVER_NAME =${{ secrets.SERVER_NAME }} >> .env
        echo CHANNEL_ID =${{ secrets.CHANNEL_ID }} >> .env

    - name: install dependencies
      run: npm ci

    - name: build project
      run: npm run build
      
    - name: test project
      run: npm run test